language: node_js
language: java
node_js:
  - 6
jdk:
  - oraclejdk8
before_script:
  - npm install -g mocha
  - git clone https://github.com/gwuhaolin/spring-data-rest-js-backend.git
  - cd spring-data-rest-js-backend
  - mvn spring-boot:run